### ISSUE TITLE
Transmittron will not connecto mosquitto broker v2.0.12

### ISSUE THREAD

**Issue by ilias-pat** [Rapatas/transmitron#18]
Transmittron will not connecto mosquitto broker v2.0.12. Possibly something to do with the MQTT protocol version used?

Observed in Windows build.

**Comment by Rapatas** [comment]
Thank you for identifying this issue!

The `timeout` and `keep-alive` fields of the broker options were parsed as milliseconds. When set in the paho client they were converted to seconds (because the values were so small, they were converted to `0`). This in turn triggers a bug in the `mosquitto v2.0.12` broker that drops connections with `keep-alive` set to `0` (https://github.com/eclipse/mosquitto/issues/2309).

The parsing is now fixed in the develop branch, but keep in mind that setting `keep-alive` to `0` will still drop the connection on `mosquitto v2.0.12`.
